[platformio]
default_envs = esp32-s3-devkitc-1-n32r16v

[env:esp32-s3-devkitc-1-n32r16v]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1-n32r16v
board_upload.flash_size = 32MB
board_build.flash_mode = opi
board_build.arduino.memory_type = opi_opi
board_build.psram_type = opi
board_build.partitions = partitions/partitions_32mb.csv
upload_speed = 460800
monitor_speed = 115200
build_flags =
  -DBOARD_HAS_PSRAM
  -DESP32
  -DESP32S3
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DDEFAULT_AP_SSID=\"ESP32-MEDIA\"
  -DMAX_UPLOAD_BYTES=20971520
  -DFW_BUILD_BOARD=\"esp32-s3-devkitc-1-n32r16v\"
  -DFW_FLASH_SIZE=\"32MB\"
  -DFW_FLASH_MODE=\"opi\"
  -DFW_MEMORY_TYPE=\"opi_opi\"
  -DFW_PSRAM_TYPE=\"opi\"
  -DFW_PARTITIONS_CSV=\"partitions/partitions_32mb.csv\"
