name: Feature request (automation-ready)
description: Create an automation-ready feature request with acceptance criteria + test plan.
title: "[Feature] "
labels: ["feature"]
body:
  - type: textarea
    id: request
    attributes:
      label: Request
      description: "Describe the feature in plain language."
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria (binary)
      description: "List numbered pass/fail checks. Prefer referencing ACCEPTANCE.md items when applicable."
      placeholder: |
        1) ...
        2) ...
    validations:
      required: true
  - type: textarea
    id: testplan
    attributes:
      label: Test plan
      description: "Which CI checks prove this? What manual/HIL evidence is required (if any)?"
      placeholder: |
        - CI: ...
        - Manual: ...
        - HIL: ...
    validations:
      required: true
  - type: dropdown
    id: risk
    attributes:
      label: Risk
      options:
        - low
        - med
        - high
    validations:
      required: true
